"""empty message

Revision ID: 231e997a33b9
Revises: 49e849fc113a
Create Date: 2026-09-25 22:46:26.261298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231e997a33b9'
down_revision = '49e849fc113a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh',
    sa.Column('id_U', sa.Integer(), nullable=False),
    sa.Column('acces', sa.String(length=200), nullable=False),
    sa.Column('refresh', sa.String(length=200), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_U'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_U')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh')
    # ### end Alembic commands ###
